### ISSUE TITLE
Can't add Notion account on Vivaldi

### ISSUE THREAD

**Issue by AnFlare** [webclipper/web-clipper#442] opened 2020-06-10 08:28 UTC
**Describe the bug**

Can't add Notion account.
It just says "Repository not Support Database" and nothing happens.

**To Reproduce**

Clipper icon -> Account -> Bind account -> Type: Notion.

**Expected behavior**

After clicking Type: Notion, it should ask for login+pass and add account.

**please complete the following information**

- Notebook: Notion
- Browser: Vivaldi 3.0.1874.38
- Version 1.23.0

**Comment by mzandvliet** [comment] 2020-07-04 11:19
Same here.

web-clipper version: 1.23.0

Vivaldi | 3.1.1929.45 (Stable channel) (64-bit)
Revision | 1eb3263017ed42270818939fbff241845938a81f
OS | Windows 10 OS Version 1909 (Build 18363.900)

**Comment by AnFlare** [comment] 2020-07-28 11:16
@mzandvliet 
As an author don't answer anything, written in English, I try to give a hint. It seems that this issue is linked to cookies and ability to read/access them. (One of my fellows achieved to start it on Chrome, where the same behaviour was).
Unfortunately, I can't point out exactly what and how should be done, because I've moved to Firefox recently and it works nice on it.

**Comment by DiamondYuan** [comment] 2020-08-19 02:46
Fixed in 1.26.0.

Use release 1.26.0 or release canary.

**Comment by DiamondYuan** [comment] 2020-08-19 02:46
@AnFlare  @mzandvliet

**Closed by DiamondYuan** 2020-08-19 02:46 UTC

**Comment by Sylphystia** [comment] 2020-09-18 10:46
The issue is present in version 1.26.1.
